export const AUTH_ROUTE = 'AUTH_ROUTE';
export const REGISTRATION_ROUTE = 'REGISTRATION_ROUTE';

export const WALLET_ROUTE = 'WALLET';
export const CREATE_WALLET_ROUTE = 'CREATE_WALLET';

export const TRANSFER_ROUTE = 'TRANSFER_ROUTE';
export const TRANSFER_SUMMARY_ROUTE = 'TRANSFER_SUMMARY_ROUTE';

export const COINS_GENERATION_ROUTE = 'COINS_GENERATION_ROUTE';
export const COINS_GENERATION_SUMMARY_ROUTE = 'COINS_GENERATION_SUMMARY_ROUTE';

export const SETTINGS_ROUTE = 'SETTINGS_ROUTE';

export enum ROUT {
  MAIN = '/',
  AUTH = '/auth',
  REGISTRATION = '/registration',

  WALLET = '/wallet',
  CREATE_WALLET = '/create-wallet',

  TRANSFER = '/transfer',
  TRANSFER_SUMMARY = '/transfer-summary',

  COINS_GENERATION = '/coins-generation',
  COINS_GENERATION_SUMMARY = '/coins-generation-summary',

  SETTINGS = '/settings',
}

export const ROUTES = {
  [AUTH_ROUTE]: ROUT.AUTH,
  [REGISTRATION_ROUTE]: ROUT.REGISTRATION,

  [WALLET_ROUTE]: ROUT.WALLET,
  [CREATE_WALLET_ROUTE]: ROUT.CREATE_WALLET,

  [TRANSFER_ROUTE]: ROUT.TRANSFER,
  [TRANSFER_SUMMARY_ROUTE]: ROUT.TRANSFER_SUMMARY,

  [COINS_GENERATION_ROUTE]: ROUT.COINS_GENERATION,
  [COINS_GENERATION_SUMMARY_ROUTE]: ROUT.COINS_GENERATION_SUMMARY,

  [SETTINGS_ROUTE]: ROUT.SETTINGS,
};
