/** auth * */
export const LOCAL_STORAGE_ACCESS_TOKEN_KEY = 'ACCESS_TOKEN';
export const LOCAL_STORAGE_REFRESH_TOKEN_KEY = 'REFRESH_TOKEN';
export const LOCAL_STORAGE_TOKEN_TYPE_KEY = 'TOKEN_TYPE';
export const LOCAL_STORAGE_EXPIRES_IN_KEY = 'EXPIRES_IN';

// export const LOCAL_STORAGE_TOKEN_KEY = 'TOKEN';
// export const LOCAL_STORAGE_LOGIN_KEY = 'LOGIN';
// export const LOCAL_STORAGE_ROLE_KEY = 'ROLE';

export const LOCAL_STORAGE_PUBLIC_KEY = 'PUBLIC_KEY';
export const LOCAL_STORAGE_RECEIVE_PUBLIC_KEY = 'RECEIVE_PUBLIC_KEY';
export const LOCAL_STORAGE_TRANSFER_AMOUNT_KEY = 'TRANSFER_AMOUNT';
export const LOCAL_STORAGE_GENERATED_COINS_COUNT_KEY = 'LOCAL_STORAGE_GENERATED_COINS_COUNT_KEY';
